# Generated by Django 4.0.2 on 2022-02-20 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20210502_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 11, 33, 13, 822214)),
        ),
        migrations.AlterField(
            model_name='editprofileevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 11, 33, 13, 823388)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 11, 33, 13, 822466)),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 11, 33, 13, 822970)),
        ),
        migrations.AlterField(
            model_name='logoutevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 11, 33, 13, 823630)),
        ),
        migrations.AlterField(
            model_name='registerevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 11, 33, 13, 822766)),
        ),
        migrations.AlterField(
            model_name='viewpageevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 11, 33, 13, 823182)),
        ),
    ]
